DROP TABLE IF EXISTS tickets CASCADE;
DROP TABLE IF EXISTS departures CASCADE;
DROP TABLE IF EXISTS schedules CASCADE;
DROP TABLE IF EXISTS buses CASCADE;
DROP TYPE IF EXISTS ticket_status_enum;
DROP TYPE IF EXISTS departure_status_enum;
